AppraisalParams:
  G: 1
  L: 5
  Lamda_p_min: 0.5
  M: 2
  N: 3
  P_z_C_scale: 19.75
  constraint_gradient_multiplier: 1.0
  constraint_subsampling: 8
  desirability_scale_factor: 0.1
  distance_buffer: 0.05
  info_gain_scale_factor: 2.0
  information_gain_subsampling: 3
  information_gradient_multiplier: 1.0
  progress_scale_factor: 0.01
Map_order: true
PlanningParams:
  K: 1
  a_support:
  - 2
  - 2
  gamma: 0.2
  initial_lr: 0.05
  movement_3_sigma: 0.2
  svi_epochs: 30
ReflectiveAttentionMechanism:
  name: damgaard2022AKS
  params:
    N_posterior_samples: 30
T_delta: 2
base_configs_file: configs/damgaard2022AKS/configs.yaml
cpu_cores: 1
goalPosition:
  x: 0.0
  y: 0.0
goal_zone_est_error_3_sigma: 0.0
goal_zone_radius: 0.0
imageScaling: 3
initial_3_sigma: 0.2
json_dir: ../../HouseExpo/json/
lidar:
  P_hit: 0.99999
  P_max: 0.0
  P_rand: 1.0e-05
  P_short: 0.0
  fov: 360
  lambda_short: None
  range: 2
  resolution: 1
  sigma_hit: 0.1
map_id_set: map_ids.txt
meter2pixel: 25
mode: 0
obstacle:
  number: 0
  size:
    max: 0.6
    min: 0.2
plotWhileSim: true
randomGoal: false
reachGoalMode: false
resetRandomPose: 1
return_Mode: mean
robotRadius: 0.2
slamError:
  angular: 0
  linear: 0
startPose:
  theta: 0
  x: 12
  y: 5
t_max: 200
useStartPosesFromLastExperiment: false
